 
# Schema.Yaml file ---> contia s the Schema that we want the trian and test dataset to have . 
# Since for data valdiation wee wnat to make sure of thsi strucutr ebefore passing it to ML model . (GIGO problem )
# AND ALSO APSS DATA TYPE OF CIL WE WNT TO HABE 
# CATEGORIZE COLS IN DIFF. CATEGORIES 


# COLUMN OF DATASET 
 columns:
  - id: int
  - Gender: category
  - Age: int
  - Driving_License: int
  - Region_Code: float
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int


 numerical_columns:
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response

 categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

 drop_columns: _id

# for data transformation (SACLING OFFEATURE STO SAME RANGE )

# FOR STANDARIZATION USING  Z-SCORE 
 num_features:
  - Age
  - Vintage

# FOR MIN-MAXSCLAING 
 mm_columns:
  - Annual_Premium